'use strict';

/*
  CHARACTER ROSTER — Cuban Double-Nine Dominos
  -----------------------------------------------
  Real family characters replace TBD placeholders.
  Portraits go in assets/characters/ named by portraitFile.
  Silhouette fallback: assets/characters/silhouette.svg

  aiStrategy values (matched in ai.js):
    'random'    - plays any valid tile randomly          (Level 0–2)
    'greedy'    - sheds highest-pip tiles fast           (Level 3–4)
    'defensive' - limits opponent options                (Level 5–7)
    'strategic' - pip management + future-move scoring   (Level 8–10)
    'expert'    - full lookahead + hand inference        (Level 11+)
*/

const CHARACTERS = [
  {
    id: 'libby',
    name: 'Libby',
    level: 0,
    difficulty: 'tutorial',
    portraitFile: 'Libby.png',
    hometown: 'Miami, FL',
    archetype: 'Tutorial NPC',
    playstyle: 'Pure Innocence',
    trait: 'Chaotic Adorable',
    skills: [
      'Button mashing',
      'Smiling at critical moments',
      'Accidentally touching dominoes',
    ],
    specialAbility: {
      name: 'Chaos Gremlin',
      description: 'All players lose concentration when Libby enters the room.',
    },
    weakness: 'Snack distractions.',
    quote: 'I wanna play too!',
    bio: 'Libby is technically not a competitive player yet, but her presence changes the energy of the table completely. Future potential remains unknown.',
    aiStrategy: 'random',
  },
  {
    id: 'alex',
    name: 'Alex',
    level: 1,
    difficulty: 'beginner',
    portraitFile: 'Alex.png',
    hometown: 'Miami, FL',
    archetype: 'Confused Recruit',
    playstyle: 'Random Survival',
    trait: 'Accidentally dangerous',
    skills: [
      'Occasionally lucky',
      'Enthusiastic participation',
      'Learns slowly under pressure',
    ],
    specialAbility: {
      name: "Beginner's Luck",
      description: "Rare chance to accidentally ruin advanced players' setups.",
    },
    weakness: 'Everything.',
    quote: 'Wait… why was that bad?',
    bio: "Alex is still learning table etiquette, strategy, and rhythm. Veteran players simultaneously fear and pity him because randomness is surprisingly dangerous.",
    aiStrategy: 'random',
  },
  {
    id: 'jt',
    name: 'JT',
    level: 3,
    difficulty: 'easy',
    portraitFile: 'JT.png',
    hometown: 'Miami, FL',
    archetype: 'Young Gun',
    playstyle: 'Fast Instinct Learner',
    trait: 'Rising prodigy',
    skills: [
      'Learns patterns quickly',
      'Aggressive experimentation',
      'Good confidence',
      'Fast adaptation',
    ],
    specialAbility: {
      name: 'Hot Streak',
      description: 'JT becomes significantly stronger after consecutive wins.',
    },
    weakness: 'Impatience.',
    quote: 'Run it back.',
    bio: 'JT has future talent written all over him. Still rough around the edges, but dangerous because he mixes gaming mentality with natural instincts. Veterans are beginning to notice.',
    aiStrategy: 'greedy',
  },
  {
    id: 'bryson',
    name: 'Bryson',
    level: 4,
    difficulty: 'easy',
    portraitFile: 'Bryson.png',
    hometown: 'Miami, FL',
    archetype: 'Reckless Rookie',
    playstyle: 'Emotional Aggressor',
    trait: 'Fearlessly chaotic',
    skills: [
      'Fearless plays',
      'Quick reactions',
      'Momentum-based confidence',
    ],
    specialAbility: {
      name: 'Send It',
      description: 'Bryson gains confidence after risky plays succeed.',
    },
    weakness: 'Predictable aggression.',
    quote: 'We ball.',
    bio: 'Bryson plays like someone trying to skip the tutorial. Bold, chaotic, and occasionally brilliant. He has picked up enough patterns to be consistently dangerous — he still crashes sometimes, but now he also wins.',
    aiStrategy: 'greedy',
  },
  {
    id: 'john',
    name: 'John',
    level: 5,
    difficulty: 'medium',
    portraitFile: 'John.png',
    hometown: 'Miami, FL',
    archetype: 'Adaptive Hustler',
    playstyle: 'Strategic Opportunist',
    trait: 'Psychologically cunning',
    skills: [
      'Reads momentum well',
      'Good mid-game recovery',
      'Strong psychological banter',
      'Occasionally overcommits trying to outsmart the table',
    ],
    specialAbility: {
      name: 'Lo Siento',
      description: 'Once per match, John can force opponents to second-guess a confident move through pure table energy and distraction.',
    },
    weakness: 'Can get too experimental chasing a big-brain play.',
    quote: 'Lo siento… no habla español.',
    bio: "John is the player who studies people as much as dominoes. He enjoys the social warfare almost as much as winning. He's dangerous when underestimated and tends to evolve throughout a night of games. Not the strongest technical player, but one of the hardest to mentally lock down.",
    aiStrategy: 'defensive',
  },
  {
    id: 'robert',
    name: 'Robert',
    level: 5,
    difficulty: 'medium',
    portraitFile: 'Robert.png',
    hometown: 'Havana, Cuba',
    archetype: 'Old School Grinder',
    playstyle: 'Methodical Pressure',
    trait: 'Classically disciplined',
    skills: [
      'Strong fundamentals',
      'Excellent patience',
      'Efficient blocking',
      'Reliable consistency',
    ],
    specialAbility: {
      name: 'Veteran Presence',
      description: 'Less experienced players become nervous against Robert.',
    },
    weakness: 'Can struggle against hyper-chaotic players.',
    quote: 'Slow down. Think.',
    bio: 'Robert represents old-school domino discipline. Not flashy, not loud, just solid. He wins through positioning, patience, and forcing mistakes.',
    aiStrategy: 'defensive',
  },
  {
    id: 'kat',
    name: 'Kat',
    level: 5,
    difficulty: 'medium',
    portraitFile: 'Kat.png',
    hometown: 'Miami, FL',
    archetype: 'The Good Time',
    playstyle: 'Intuitive Fun',
    trait: 'Disarmingly sharp',
    skills: [
      'Reads the table without trying',
      'Adapts without overthinking',
      'Keeps the energy easy',
      'Wins without anyone noticing she was competing',
    ],
    specialAbility: {
      name: 'Just Having Fun',
      description: "Kat plays relaxed enough that opponents stop tracking her — right when she starts closing them out.",
    },
    weakness: 'Can get distracted when the conversation gets good.',
    quote: "We're just having fun... right?",
    bio: "Kat doesn't need to win — she just enjoys the game. Which is exactly why she's dangerous. She plays without ego, adjusts without drama, and somehow always ends up in a better position than you expected. Nobody at the table is quite sure when Kat got good.",
    aiStrategy: 'defensive',
  },
  {
    id: 'emily',
    name: 'Emily',
    level: 6,
    difficulty: 'medium',
    portraitFile: 'Emily.png',
    hometown: 'Miami, FL',
    archetype: 'Social Predator',
    playstyle: 'Emotional Manipulator',
    trait: 'Socially weaponized',
    skills: [
      'Reads reactions well',
      'Strong conversational distraction',
      'Opportunistic finishing',
      'Good pressure handling',
    ],
    specialAbility: {
      name: 'Side Eye',
      description: 'Emily gains advantage whenever opponents start explaining themselves too much.',
    },
    weakness: 'Can lose focus if games drag too long.',
    quote: 'Oh NOW you wanna play smart?',
    bio: 'Emily weaponizes personality. She thrives in loud family games where emotions start overriding logic. Not the strongest pure strategist, but extremely dangerous socially.',
    aiStrategy: 'defensive',
  },
  {
    id: 'stritch',
    name: 'Stritch',
    level: 6,
    difficulty: 'medium',
    portraitFile: 'Stritch.png',
    hometown: 'Miami, FL',
    archetype: 'The Grinder',
    playstyle: 'Steady Competitor',
    trait: 'Pleasantly relentless',
    skills: [
      'Consistent tile management',
      'Competitive without the ego',
      'Reads patterns steadily',
      'Rarely cracks under pressure',
    ],
    specialAbility: {
      name: 'Game Sense',
      description: 'Stritch plays every round like a game seven — focused, composed, and quietly dangerous.',
    },
    weakness: 'Can be too methodical against chaotic players.',
    quote: 'Good game though.',
    bio: "Stritch brings a sports mentality to the domino table — disciplined, consistent, and relentlessly competitive in the best way. He makes you work for every round, never tilts, and is always ready to shake hands after. Underestimate the hat at your own risk.",
    aiStrategy: 'defensive',
  },
  {
    id: 'mikey',
    name: 'Mikey',
    level: 7,
    difficulty: 'hard',
    portraitFile: 'Mikey.png',
    hometown: 'Miami, FL',
    archetype: 'Chaos Engine',
    playstyle: 'Momentum Gambler',
    trait: 'Gloriously unpredictable',
    skills: [
      'High-risk clutch plays',
      'Natural luck',
      'Strong comeback energy',
      'Unpredictable sequencing',
    ],
    specialAbility: {
      name: 'Wildcard',
      description: 'Mikey occasionally makes objectively terrible moves that somehow work perfectly.',
    },
    weakness: 'Consistency.',
    quote: 'Trust me bro, I got this.',
    bio: "Nobody is ever fully comfortable playing Mikey because even Mikey doesn't know what Mikey is doing sometimes. Dangerous in casual games and emotionally fueled matches.",
    aiStrategy: 'strategic',
  },
  {
    id: 'poppy',
    name: 'Poppy',
    level: 7,
    difficulty: 'hard',
    portraitFile: 'Poppy.png',
    hometown: 'Havana, Cuba',
    archetype: 'The Crafty Elder',
    playstyle: 'Patient Trickster',
    trait: 'Deceptively shrewd',
    skills: [
      'Masters the slow game',
      'Lulls opponents into false comfort',
      'Decades of hidden pattern knowledge',
      'Knows every bluff at the table',
    ],
    specialAbility: {
      name: 'Old Dog',
      description: 'Poppy reveals a trick no one saw coming just when opponents think they have him cornered.',
    },
    weakness: 'Sometimes enjoys the trap more than the win.',
    quote: 'Sit down, mijo. Let me show you something.',
    bio: "Poppy has been playing dominos since Cuba. That hat has seen more table wars than most players have years. Don't let the warm smile fool you — he's been setting his trap since the second tile dropped.",
    aiStrategy: 'strategic',
  },
  {
    id: 'mawmaw',
    name: 'MawMaw',
    level: 8,
    difficulty: 'hard',
    portraitFile: 'MawMaw.png',
    hometown: 'Miami, FL',
    archetype: 'The Quiet Storm',
    playstyle: 'Warm But Ruthless',
    trait: 'Dangerously underestimated',
    skills: [
      'Plays tiles with surgical precision',
      'Never reveals emotion',
      'Outlasts impatient players every time',
      'Reads family tendencies better than anyone',
    ],
    specialAbility: {
      name: 'Bless Your Heart',
      description: "MawMaw smiles sweetly and dismantles your hand. The kinder she seems, the worse your position.",
    },
    weakness: 'Occasionally lets family members off the hook. Occasionally.',
    quote: 'Mija, I watched your father make that same mistake.',
    bio: "MawMaw has been sitting at this table her whole life. She knows everyone's tells, everyone's habits, and exactly when to close the board. Players always feel respected — right up until they lose.",
    aiStrategy: 'strategic',
  },
  {
    id: 'yve',
    name: 'Yve',
    level: 9,
    difficulty: 'hard',
    portraitFile: 'Yve.png',
    hometown: 'Miami, FL',
    archetype: 'Silent Queen',
    playstyle: 'Precision Controller',
    trait: 'Ice-cold precision',
    skills: [
      'Elite memory tracking',
      'Calm under pressure',
      'Punishes mistakes instantly',
      'Reads team dynamics exceptionally well',
    ],
    specialAbility: {
      name: 'Cold Table',
      description: 'The longer the match goes, the stronger Yve becomes. Opponents slowly lose confidence and tempo.',
    },
    weakness: 'Occasionally too patient when an aggressive finish is available.',
    quote: 'You already lost two hands ago.',
    bio: "Yve rarely needs to talk trash because her gameplay does it for her. She quietly dismantles aggressive players and thrives in long, tactical matches. Many players realize too late they've been trapped three turns ago.",
    aiStrategy: 'strategic',
  },
  {
    id: 'manny',
    name: 'Manny',
    level: 10,
    difficulty: 'expert',
    portraitFile: 'Manny.png',
    hometown: 'Havana, Cuba',
    archetype: 'The Elder Statesman',
    playstyle: 'Deliberate Control',
    trait: 'Quietly formidable',
    skills: [
      'Deep positional awareness',
      'Calm decision-making under pressure',
      'Decades of accumulated table knowledge',
      'Forces opponents to play his pace',
    ],
    specialAbility: {
      name: 'El Veterano',
      description: "Manny's experience shows in every move. He rarely makes mistakes, and the ones he does make are calculated.",
    },
    weakness: 'Art and Yoli have surpassed his intensity — he plays for the love of the game now.',
    quote: "I've seen this before. Fifty years ago.",
    bio: "Manny is where Art and Yoli learned the game. Experienced, composed, and still dangerous — but he plays with patience where they play with fire. Beating Manny is a real accomplishment. Beating Art or Yoli is a different conversation entirely.",
    aiStrategy: 'expert',
  },
  {
    id: 'yoli',
    name: 'Yoli',
    level: 11,
    difficulty: 'expert',
    portraitFile: 'Yoli.png',
    hometown: 'Havana, Cuba',
    archetype: 'The Matriarch',
    playstyle: 'Elegant Assassin',
    trait: 'Legendarily composed',
    skills: [
      'Master-level patience',
      'Team synchronization',
      'Emotional control',
      'Trap-setting expertise that rivals anyone at the table',
    ],
    specialAbility: {
      name: 'La Reina',
      description: 'Yoli gains momentum whenever opponents become emotional or start arguing. The more pressure they feel, the calmer she gets.',
    },
    weakness: 'Art is the one opponent she has never fully solved.',
    quote: 'Ay mijo… that was your move?',
    bio: "Yoli is the only player at this table who can match Art move for move — and sometimes outmaneuver him entirely. Calm, smiling, and quietly orchestrating destruction, she's beaten Art enough times to make him respect her. Everyone else she simply dismantles.",
    aiStrategy: 'expert',
  },
  {
    id: 'art',
    name: 'Art',
    level: 12,
    difficulty: 'expert',
    portraitFile: 'Art.png',
    hometown: 'Miami, FL',
    archetype: 'Domino Warlord',
    playstyle: 'Aggressive Tactical Enforcer',
    trait: 'The undisputed apex',
    skills: [
      'Elite board control',
      'Relentless psychological pressure',
      'Reads the entire table simultaneously',
      'No one closes a game faster or harder',
    ],
    specialAbility: {
      name: 'Table Slam',
      description: 'Art forces the pace so aggressively that opponents stop thinking and start reacting. By then, it is already over.',
    },
    weakness: 'Yoli is the only one who has ever made him nervous.',
    quote: 'Just go ahead and draw.',
    bio: "Art is the final boss. Loud, relentless, and decades of pure instinct built into every play. He doesn't just beat opponents — he makes them feel like they never had a chance. Nobody at this table hits harder, thinks faster, or closes a game with more authority. You have been warned.",
    aiStrategy: 'expert',
  },
];

// Lookup helper
const CharacterDB = {
  getById(id) {
    return CHARACTERS.find(c => c.id === id) || null;
  },
  getAll() {
    return CHARACTERS;
  },
  difficultyOrder: ['tutorial', 'beginner', 'easy', 'medium', 'hard', 'expert', 'master'],
};
